# qbd submitscript (variant "default"), ported from simfactory2
# mdb/submitscripts/qbd.sub (PBS/Torque; upstream regenerated by
# simfactory-configure.py on 2026-07-07 — the scheduler flipped SLURM->PBS).
#
# .py variant (design §6.1): the `-q @QUEUE@` directive is guarded by
# `if QUEUE:` and restart chaining is re-added as `-W depend=afterany` guarded
# by CHAINED_JOB_ID (see below) — cactup's @NAME@ engine is literal-only (D7),
# so both conditionals move into Python.
#
# Changes vs. simfactory (design §6.3, §8.3.1):
#   @NODE_PROCS@ -> TASKS_PER_NODE
#   -o uses STDOUT_FILE (same @RUNDIR@/@SIMULATION_NAME@.out default, but it
#     honors cactup's -o flag); `-j oe` still folds stderr into it
#   mail directives guarded by `if EMAIL:` (the old script emitted them always)
#   `-q @QUEUE@` guarded by `if QUEUE:` — the upstream `queue` field is empty,
#     so @QUEUE@/QUEUE resolves to "" and no `-q` directive is emitted (see the
#     placeholder queue in meta.toml)
#   restart chaining: the auto-generated PBS script dropped it; re-added as
#     `-W depend=afterany` guarded by CHAINED_JOB_ID (cactup restart chaining,
#     matching the sibling LSU/LONI PBS machine `qb`)
#   @SIMFACTORY@ run --basedir=… -> @CACTUP@ sim run --installation/--sim-dir/
#     --machine (the compute-node re-invocation locator)

lines = ["#! /bin/bash"]
lines.append("#PBS -l walltime={0}".format(WALLTIME))
lines.append("#PBS -l nodes={0}:ppn={1}".format(NODES, TASKS_PER_NODE))
if QUEUE:
    lines.append("#PBS -q {0}".format(QUEUE))
lines.append("#PBS -A {0}".format(ALLOCATION))
lines.append("#PBS -N {0}".format(SIMULATION_NAME))
lines.append("#PBS -j oe")
if CHAINED_JOB_ID:
    lines.append("#PBS -W depend=afterany:{0}".format(CHAINED_JOB_ID))
if EMAIL:
    lines.append("#PBS -m abe")
    lines.append("#PBS -M {0}".format(EMAIL))
lines.append("#PBS -o {0}".format(STDOUT_FILE))

# env-setup is NOT auto-prepended for .py variants (design §6.1); place it
# after the directive header.
lines.append(ENV_SETUP)

lines.append("cd {0}".format(SOURCEDIR))
lines.append(
    "exec {0} sim run {1} --installation={2} --sim-dir={3} --machine={4}"
    " --restart-id={5}".format(
        CACTUP, SIMULATION_NAME, ALIAS, SIMULATION_DIR, MACHINE,
        RESTART_ID,
    )
)

print("\n".join(lines))
