#! /bin/bash
# qbd runscript (variant "default"), ported from simfactory2
# mdb/runscripts/qbd.run (upstream regenerated by simfactory-configure.py on
# 2026-07-07 — a plain native launch; the old Singularity-image srun is gone).
#
# Variable renames vs. simfactory (design §6.3):
#   NUM_PROCS   -> @TASKS@
#   NUM_THREADS -> @CPUS_PER_TASK@
# Metadata dir SIMFACTORY/ -> .cactup/ (design §9.3).

echo "Preparing:"
set -x
set -e

cd @RUNDIR@-active

module list
echo "Checking:"
pwd
hostname
date

echo "Environment:"
export CACTUS_NUM_PROCS=@TASKS@
export CACTUS_NUM_THREADS=@CPUS_PER_TASK@
export GMON_OUT_PREFIX=gmon.out
export OMP_NUM_THREADS=@CPUS_PER_TASK@
export OMP_STACKSIZE=8192
env | sort > .cactup/ENVIRONMENT

echo "Starting:"
export CACTUS_STARTTIME=$(date +%s)

if [ ${CACTUS_NUM_PROCS} = 1 ]; then
    @EXECUTABLE@ -L 3 @PARFILE@
else
    mpirun -np @TASKS@ @EXECUTABLE@ -L 3 @PARFILE@
fi

echo "Stopping:"
date
echo "Done."
