#! /bin/bash
# qbd runscript (variant "default"), ported from simfactory2
# mdb/runscripts/qbd.run (upstream regenerated by simfactory-configure.py on
# 2026-07-07 — that regeneration emitted a bare mpirun launch, but mpirun does
# not work for multi-task jobs on QB4, so that port was bogus). The launch
# below is srun instead, run inside the allocation the submitscript
# (mdb/qbd/submitscripts/default.py) already requested via #SBATCH
# -N/-n/--cpus-per-task/--gres/--gpus-per-task — this script must not pass
# any of -A/-p/-N/--gres itself. Mirrors db1's runscripts/default.sh.
#
# Variable renames vs. simfactory (design §6.3):
#   NUM_PROCS   -> @TASKS@
#   NUM_THREADS -> @CPUS_PER_TASK@
# Metadata dir SIMFACTORY/ -> .cactup/ (design §9.3).

echo "Preparing:"
set -x
set -e

cd @RUNDIR@-active

module list
echo "Checking:"
pwd
hostname
date

echo "Environment:"
export CACTUS_NUM_PROCS=@TASKS@
export CACTUS_NUM_THREADS=@CPUS_PER_TASK@
export GMON_OUT_PREFIX=gmon.out
export OMP_NUM_THREADS=@CPUS_PER_TASK@
export OMP_PLACES=cores
export OMP_STACKSIZE=8192
env | sort > .cactup/ENVIRONMENT

echo "Starting:"
export CACTUS_STARTTIME=$(date +%s)

time srun -u --overlap -n @TASKS@ \
    --cpus-per-task=@CPUS_PER_TASK@ \
    --gpus-per-task=@GPUS_PER_TASK@ \
    --gres-flags=allow-task-sharing \
    @EXECUTABLE@ -L 3 @PARFILE@

echo "Stopping:"
date
echo "Done."
