#! /bin/bash
# qbd runscript (variant "default"), ported from simfactory2
# mdb/runscripts/qbd.run (upstream regenerated by simfactory-configure.py on
# 2026-07-07 — that regeneration emitted a bare mpirun launch, but mpirun does
# not work for multi-task jobs on QB4, so that port was bogus). The launch
# below is srun instead, run inside the allocation the submitscript
# (mdb/qbd/submitscripts/default.py) already requested via #SBATCH
# -N/-n/--cpus-per-task/--gres/--gpus-per-task — this script must not pass
# any of -A/-p/-N/--gres itself. Mirrors db1's runscripts/default.sh.
#
# Variable renames vs. simfactory (design §6.3):
#   NUM_PROCS   -> @TASKS@
#   NUM_THREADS -> @CPUS_PER_TASK@
# Metadata dir SIMFACTORY/ -> .cactup/ (design §9.3).

echo "Preparing:"
set -x
set -e

cd @RUNDIR@-active

module list
echo "Checking:"
pwd
hostname
date

echo "Environment:"
export CACTUS_NUM_PROCS=@TASKS@
export CACTUS_NUM_THREADS=@CPUS_PER_TASK@
export GMON_OUT_PREFIX=gmon.out
export OMP_NUM_THREADS=@CPUS_PER_TASK@
export OMP_PLACES=cores
export OMP_STACKSIZE=8192
env | sort > .cactup/ENVIRONMENT

# Optional profiler wrapper (mixed-precision performance work). Set the
# variable in the shell that runs `cactup sim submit`; sbatch propagates the
# environment to the job. Unset: this block is inert.
#   CACTUP_PROFILE=nsys   one nsys report per task (CUDA + NVTX + MPI)
#   CACTUP_PROFILE=ncu    ncu on task 0 only: 40 launches after skipping 20,
#                         SpeedOfLight + MemoryWorkloadAnalysis sections;
#                         CACTUP_NCU_KERNELS overrides the kernel-name regex
PROF_WRAPPER=
case "${CACTUP_PROFILE:-}" in
  nsys)
    PROF_WRAPPER="nsys profile --trace=cuda,nvtx,mpi --sample=none --cpuctxsw=none --cuda-memory-usage=true --force-overwrite=true -o profile.task%q{SLURM_PROCID}" ;;
  ncu)
    cat > ./prof-ncu.sh <<'EOS'
#!/bin/bash
if [ "${SLURM_PROCID:-0}" = 0 ]; then
  exec ncu --target-processes all --launch-skip 20 --launch-count 40 \
    --kernel-name "regex:${CACTUP_NCU_KERNELS:-copy|FillBoundary|ParallelFor}" \
    --section SpeedOfLight --section MemoryWorkloadAnalysis \
    --force-overwrite -o profile.ncu "$@@"
else
  exec "$@@"
fi
EOS
    chmod +x ./prof-ncu.sh
    PROF_WRAPPER=./prof-ncu.sh ;;
esac

export OMPI_MCA_pml=ucx
export OMPI_MCA_btl=^openib

echo "Starting:"
export CACTUS_STARTTIME=$(date +%s)

time srun -u --overlap -n @TASKS@ \
    --cpus-per-task=@CPUS_PER_TASK@ \
    --gpus-per-task=@GPUS_PER_TASK@ \
    --gres-flags=allow-task-sharing \
    ${PROF_WRAPPER} @EXECUTABLE@ -L 3 @PARFILE@

echo "Stopping:"
date
echo "Done."
