//! What this binary is: a CI distribution build or a dev build, and which
//! MDB generation it reads. The constants are generated by `build.rs` from
//! the `CACTUP_DIST`/`CACTUP_BUILD_ID`/`CACTUP_BUILD_DATE` stamp CI sets and
//! from `mdb/GENERATION`.
//!
//! Dev vs dist is decided by that stamp, never by the cargo profile: a
//! distribution build syncs its MDB clone, updates itself and freezes itself
//! for jobs; every local cargo build, debug or release, reads the repo's
//! `mdb/` and does none of that.

/// The CI build stamp of a distribution build.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Stamp {
    /// The abbreviated id of the last commit that touched a build input
    /// (7-40 lowercase hex digits).
    pub id: &'static str,
    /// That commit's committer date, strict ISO 8601 (git's `%cI`).
    pub date: &'static str,
}

// Generated: `DIST: Option<Stamp>`, `MDB_GENERATION: u32`, `TARGET: &str`
// (the target triple), `GENERIC_HASH: &str` (content hash of the embedded
// `mdb/generic`), `LONG_VERSION: &str` (the `--version` text) and
// `USER_AGENT: &str`.
mod generated {
    use super::Stamp;
    include!(concat!(env!("OUT_DIR"), "/build_info_gen.rs"));
}
pub use generated::*;

/// Is this a distribution build? Always false under `cargo test`, so a
/// stamped test binary can never sync, self-update, or copy itself.
pub fn is_dist() -> bool {
    DIST.is_some() && !cfg!(test)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generation_matches_the_mdb() {
        let raw = include_str!("../mdb/GENERATION");
        assert_eq!(raw.trim().parse::<u32>().unwrap(), MDB_GENERATION);
    }

    #[test]
    fn every_generation_is_documented() {
        let doc = include_str!("../mdb/GENERATIONS.md");
        for k in 1..=MDB_GENERATION {
            let heading = format!("## Generation {k}");
            assert!(
                doc.lines().any(|line| line.trim_end() == heading),
                "mdb/GENERATIONS.md lacks a \"{heading}\" section"
            );
        }
    }

    #[test]
    fn version_strings_have_their_shape() {
        let version = crate::VERSION;
        let tail = format!(", mdb generation {MDB_GENERATION})");
        match DIST {
            Some(stamp) => {
                assert_eq!(LONG_VERSION, format!("{version} ({} {}{tail}", stamp.id, &stamp.date[..10]));
                assert_eq!(USER_AGENT, format!("cactup/{version}+{}", stamp.id));
            }
            None => {
                assert_eq!(LONG_VERSION, format!("{version} (dev build{tail}"));
                assert_eq!(USER_AGENT, format!("cactup/{version}+dev"));
            }
        }
        assert!(!is_dist(), "tests never behave as a distribution build");
        assert_eq!(GENERIC_HASH.len(), 16);
        assert!(GENERIC_HASH.bytes().all(|b| b.is_ascii_hexdigit()));
        assert!(!TARGET.is_empty());
    }

    #[test]
    fn generic_hash_fingerprints_the_embedded_generic() {
        let generic = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("mdb").join("generic");
        assert_eq!(GENERIC_HASH, crate::commands::machine::hash_machine_dir(&generic).unwrap());
    }
}
